// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "CrabyUtils.hpp"
#include "ffi.rs.h"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace reactnativecrabybase64 {
namespace modules {

class JSI_EXPORT CxxReactNativeCrabyBase64Module : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "ReactNativeCrabyBase64";
  static std::string dataPath;

  CxxReactNativeCrabyBase64Module(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxReactNativeCrabyBase64Module();

  void invalidate();
  static facebook::jsi::Value
  decodeToBytes(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  decodeToString(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  encodeString(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::reactnativecrabybase64::bridging::ReactNativeCrabyBase64> module_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
  std::shared_ptr<craby::reactnativecrabybase64::utils::ThreadPool> threadPool_;
};

} // namespace modules
} // namespace reactnativecrabybase64
} // namespace craby
