// Auto generated by Craby. DO NOT EDIT.
#include "CxxReactNativeCrabyBase64Module.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace reactnativecrabybase64 {
namespace modules {

std::string CxxReactNativeCrabyBase64Module::dataPath = std::string();

CxxReactNativeCrabyBase64Module::CxxReactNativeCrabyBase64Module(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxReactNativeCrabyBase64Module::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::reactnativecrabybase64::bridging::ReactNativeCrabyBase64>(
    craby::reactnativecrabybase64::bridging::createReactNativeCrabyBase64(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::reactnativecrabybase64::bridging::ReactNativeCrabyBase64 *ptr) { rust::Box<craby::reactnativecrabybase64::bridging::ReactNativeCrabyBase64>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::reactnativecrabybase64::utils::ThreadPool>(10);
  methodMap_["decodeToBytes"] = MethodMetadata{1, &CxxReactNativeCrabyBase64Module::decodeToBytes};
  methodMap_["decodeToString"] = MethodMetadata{1, &CxxReactNativeCrabyBase64Module::decodeToString};
  methodMap_["encodeString"] = MethodMetadata{1, &CxxReactNativeCrabyBase64Module::encodeString};
}

CxxReactNativeCrabyBase64Module::~CxxReactNativeCrabyBase64Module() {
  invalidate();
}

void CxxReactNativeCrabyBase64Module::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxReactNativeCrabyBase64Module::decodeToBytes(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeCrabyBase64Module &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::reactnativecrabybase64::bridging::decodeToBytes(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativecrabybase64::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeCrabyBase64Module::decodeToString(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeCrabyBase64Module &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::reactnativecrabybase64::bridging::decodeToString(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativecrabybase64::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeCrabyBase64Module::encodeString(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeCrabyBase64Module &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::reactnativecrabybase64::bridging::encodeString(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativecrabybase64::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace reactnativecrabybase64
} // namespace craby
