// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::react_native_craby_base_64_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::reactnativecrabybase64::bridging")]
pub mod bridging {




    extern "Rust" {
        type ReactNativeCrabyBase64;

        #[cxx_name = "createReactNativeCrabyBase64"]
        fn create_react_native_craby_base_64(id: usize, data_path: &str) -> Box<ReactNativeCrabyBase64>;

        #[cxx_name = "decodeToBytes"]
        fn react_native_craby_base_64_decode_to_bytes(it_: &mut ReactNativeCrabyBase64, b_64: &str) -> Result<String>;

        #[cxx_name = "decodeToString"]
        fn react_native_craby_base_64_decode_to_string(it_: &mut ReactNativeCrabyBase64, b_64: &str) -> Result<String>;

        #[cxx_name = "encodeString"]
        fn react_native_craby_base_64_encode_string(it_: &mut ReactNativeCrabyBase64, input: &str) -> Result<String>;
    }

}

fn create_react_native_craby_base_64(id: usize, data_path: &str) -> Box<ReactNativeCrabyBase64> {
    let ctx = Context::new(id, data_path);
    Box::new(ReactNativeCrabyBase64::new(ctx))
}

fn react_native_craby_base_64_decode_to_bytes(it_: &mut ReactNativeCrabyBase64, b_64: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.decode_to_bytes(b_64);
        ret
    })
}

fn react_native_craby_base_64_decode_to_string(it_: &mut ReactNativeCrabyBase64, b_64: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.decode_to_string(b_64);
        ret
    })
}

fn react_native_craby_base_64_encode_string(it_: &mut ReactNativeCrabyBase64, input: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.encode_string(input);
        ret
    })
}
