// Auto generated by Craby. DO NOT EDIT.
// Hash: 65458f623bf2c713
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ReactNativeCrabyBase64Spec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn decode_to_bytes(&mut self, b_64: &str) -> String;
    fn decode_to_string(&mut self, b_64: &str) -> String;
    fn encode_string(&mut self, input: &str) -> String;
}
