// Auto generated by Craby. DO NOT EDIT.
#include <CxxReactNativeCrabyBase64Module.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::reactnativecrabybase64::modules::CxxReactNativeCrabyBase64Module::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::reactnativecrabybase64::modules::CxxReactNativeCrabyBase64Module>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_rs_craby_reactnativecrabybase64_ReactNativeCrabyBase64Package_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  const char* cDataPath = env->GetStringUTFChars(jDataPath, nullptr);
  auto dataPath = std::string(cDataPath);
  env->ReleaseStringUTFChars(jDataPath, cDataPath);
  craby::reactnativecrabybase64::modules::CxxReactNativeCrabyBase64Module::dataPath = dataPath;
}
